#!/bin/env python
#
#
# CLI for starting and running Spark standalone clusters on HPC resources
#
#

from __future__ import print_function
import click
from sparkhpc import sparklsf
import subprocess

@click.group()
def cli():
    pass

@cli.command()
@click.argument('ncores')
@click.option('--walltime', default="00:30", help="Walltime in HH:MM format")
@click.option('--jobname', default='spark', help='Name to use for the job')
@click.option('--template', default='./sparkjob.lsf.template', help='Job template path')
@click.option('--driver-memory', default='2G', help='Spark driver memory', envvar='SPARK_DRIVER_MEMORY')
@click.option('--executor-memory', default='2G', help='Spark executor memory', envvar='SPARK_EXECUTOR_MEMORY')
@click.option('--wait', default=0, help='Seconds to wait until job starts')
def submit(ncores, walltime, jobname, template, driver_memory, executor_memory, wait):
    """Submit the spark cluster as an LSF job"""
    sj = sparklsf.SparkJob(ncores=ncores, walltime=walltime, jobname=jobname, template=template,
                           driver_memory=driver_memory, executor_memory=executor_memory)
    sj.submit()

    if wait: 
        print('Waiting for job to start')
        sj.wait_to_start()
        #print 'Job %s running with %d cores'%(sj.jobid, ncores)


@cli.command()
def info():
    """Get info about currently running clusters"""
    sjs = sparklsf.current_clusters()

    if len(sjs) == 0: 
        print('No Spark clusters found')

    for i,sj in enumerate(sjs): 
        print('----- Cluster %d -----'%i)
        if sparklsf.job_started(sj.jobid): 
            print('Number of cores: %s'%sj.ncores)
            print('master URL: %s'%sparklsf.master_url(sj.jobid)[0])
            print('Spark UI: %s'%sparklsf.master_ui(sj.jobid)[0])
        else: 
            print('Job %s yet started'%jobid)


@cli.command()
@click.argument('clusterid', type=click.INT)
def kill(clusterid):
    """Kill a currently running cluster"""
    sjs = sparklsf.current_clusters()
    out = subprocess.check_output(['bkill', '%s'%sjs[clusterid].jobid])
    print(out)

if __name__ == "__main__":
    cli()
